### ISSUE TITLE
What in the world?

### ISSUE THREAD

**Issue by H4SHT4GH4ZE** [itsalittleguy6/BallBrickBreak2#1]
![screen shot 2019-03-07 at 11 15 49 pm](https://user-images.githubusercontent.com/45727282/54007320-1a2dfa80-412f-11e9-8aa3-3f9221b69bdc.png)

I'm getting a dumb error

**Comment by PythonPickle** [comment]
https://www.youtube.com/watch?v=HP4R_Bqp1Nk
https://www.youtube.com/watch?v=j3yH6FfD_Wk
